name: ct_micro_commons_core_app
description:
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  ct_micro_commons_dependencies:
    path: ../ct_micro_commons_dependencies
    # git:
    #   url: "https://github.com/cuiatech/ct_micro_commons_dependencies.git"
    #   ref: "master"
  ct_micro_commons_client_https:
    path: ../ct_micro_commons_client_https
    # git:
    #   url: "https://github.com/cuiatech/ct_micro_commons_client_https.git"
    #   ref: "master"
  ct_micro_commons_shared:
    path: ../ct_micro_commons_shared
    # git:
    #   url: "https://github.com/cuiatech/ct_micro_commons_shared.git"
    #   ref: "master"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:


